#!/usr/bin/env python3
"""
UnitLang compiler - command line driver.

    python3 main.py program.ul                 compile and run on the VM
    python3 main.py program.ul --ir            also show the TAC IR
    python3 main.py program.ul --bytecode      also show the bytecode
    python3 main.py program.ul --symbols       show unit table / variables / function instances
    python3 main.py program.ul --stats         show optimizer + execution statistics
    python3 main.py program.ul --no-opt        disable the optimizer (compare with --stats)
    python3 main.py program.ul --interp        run on the reference tree-walking interpreter
    python3 main.py program.ul --check         type-check only, do not run

Exit status: 0 success, 1 compile-time error, 2 runtime error.
"""

import argparse
import sys

from pipeline import compile_source, run_vm, run_interpreter
from irgen import dump_tac
from codegen import disassemble
from quantity import RuntimeErr


def print_symbols(res):
    sym = res.analyzer.sym
    print("== Units (name, dimension, scale in base units, origin) ==")
    for u in sym.units.values():
        print(f"  {u.name:<6} {u.dim.pretty():<28} {u.scale:<14g} {u.origin}")
    print("\n== Global variables (name -> dimension) ==")
    globals_ = sym.scopes[0]
    if not globals_:
        print("  (none)")
    for name, entry in globals_.items():
        print(f"  {name:<12} {entry.dim.pretty()}")
    print("\n== Function instances inferred (dimension-polymorphic) ==")
    if not res.analyzer.instance_log:
        print("  (none)")
    for name, dims, ret in res.analyzer.instance_log:
        args = ", ".join("number" if d.is_dimensionless() else d.pretty() for d in dims)
        shown = "number" if ret.is_dimensionless() else ret.pretty()
        print(f"  {name}({args}) -> {shown}")


def print_stats(res, vm_steps=None):
    s = res.stats
    print("== Optimizer / code-generator statistics ==")
    print(f"  TAC instructions        : {s.tac_before} -> {s.tac_after}")
    print(f"  operations folded       : {s.folded}  (involving units: {s.unit_folds})")
    print(f"  unit names inlined      : {s.unit_inlines}")
    print(f"  constants propagated    : {s.propagated}")
    print(f"  dead instructions       : {s.dead}")
    print(f"  bytecode (pre -> post peephole): {s.bc_before} -> {s.bc_after}"
          f"  (peephole pairs removed: {s.peephole})")
    if vm_steps is not None:
        print(f"  instructions executed   : {vm_steps}")


def main(argv=None):
    ap = argparse.ArgumentParser(description="UnitLang compiler")
    ap.add_argument("file")
    ap.add_argument("--ir", action="store_true", help="show TAC (before and after optimization)")
    ap.add_argument("--bytecode", action="store_true", help="show generated bytecode")
    ap.add_argument("--symbols", action="store_true", help="show symbol tables")
    ap.add_argument("--stats", action="store_true", help="show optimizer statistics")
    ap.add_argument("--no-opt", action="store_true", help="disable optimizations")
    ap.add_argument("--interp", action="store_true", help="use the reference interpreter")
    ap.add_argument("--check", action="store_true", help="type-check only")
    args = ap.parse_args(argv)

    with open(args.file) as f:
        source = f.read()

    res = compile_source(source, optimize=not args.no_opt)
    for w in res.warnings:
        print(w, file=sys.stderr)
    if not res.ok:
        print(f"{res.stage} errors:", file=sys.stderr)
        for e in res.errors:
            print(f"  {e}", file=sys.stderr)
        return 1

    if args.symbols:
        print_symbols(res)
        print()
    if args.ir:
        print("---- TAC (unoptimized) ----")
        print(dump_tac(res.tac, res.irgen.dims))
        if not args.no_opt:
            print("\n---- TAC (optimized) ----")
            print(dump_tac(res.opt_tac, res.irgen.dims))
        print()
    if args.bytecode:
        print("---- Bytecode ----")
        print(disassemble(res.program))
        print()
    if args.check:
        print("Type check passed.")
        return 0

    if args.ir or args.bytecode or args.symbols:
        print("---- Program output ----")
    steps = None
    try:
        if args.interp:
            _, engine = run_interpreter(res, echo=True)
        else:
            _, engine = run_vm(res, echo=True)
            steps = engine.steps
    except RuntimeErr as e:
        print(f"Runtime error: {e}", file=sys.stderr)
        return 2
    if args.stats:
        print()
        print_stats(res, steps)
    return 0


if __name__ == "__main__":
    sys.exit(main())
